# Generated by Django 2.1 on 2018-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180910_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='Fulana(o)', max_length=150, null=True, verbose_name='Nome'),
        ),
    ]
