# Generated by Django 2.1 on 2018-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20180831_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frete',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Frete'),
        ),
        migrations.AddField(
            model_name='order',
            name='prazo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo Entrega'),
        ),
    ]
