# Generated by Django 2.1 on 2018-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20180911_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valorTotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Total'),
        ),
    ]
