# Generated by Django 2.1 on 2018-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Destaque')], default=1, max_length=2, verbose_name='Destaque'),
        ),
    ]
