# Generated by Django 2.1 on 2018-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtc/images', verbose_name='Imagem'),
        ),
    ]
