# Generated by Django 2.1 on 2018-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgfeat',
            field=models.ImageField(blank=True, null=True, upload_to='produtc/images/destaque', verbose_name='Imagem'),
        ),
    ]
