# Generated by Django 2.1 on 2018-08-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180816_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Destaque')], default=1, verbose_name='Destaque'),
        ),
    ]
