# Generated by Django 2.1 on 2018-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180816_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryshop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
