# Generated by Django 2.1 on 2018-08-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, verbose_name='Atalho')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/images', verbose_name='Imagem')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Imagens',
                'verbose_name_plural': 'Image',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Categoria')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Image', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Projetos',
                'verbose_name_plural': 'Projeto',
                'ordering': ['name'],
            },
        ),
    ]
