# Generated by Django 2.1 on 2018-08-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imagemin',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/imagesmin', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Image', verbose_name='Imagem'),
        ),
    ]
