# Generated by Django 2.1 on 2018-09-16 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_categorycatalog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Project', verbose_name='Favorito')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Projeto Favorito',
                'verbose_name_plural': 'Projetos Favoritos',
                'ordering': ['project'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproject',
            unique_together={('user', 'project')},
        ),
    ]
